const empresasDirectorio = [
  // CENTROS DE DISTRIBUCIÓN - RETAIL
  { nombre: "Walmart Chile - Centro Distribución Quilicura", region: "Metropolitana", comuna: "Quilicura", direccion: "Av. Presidente Eduardo Frei Montalva 8301", telefono: "+56222005000", email: "contacto@walmart.cl", sitioWeb: "www.walmartchile.cl", tipoIndustria: "Distribución/Retail", cargoObjetivo: "Gerente de Operaciones, Jefe de Logística" },
  { nombre: "Cencosud - Centro Distribución Santa Isabel", region: "Metropolitana", comuna: "Pudahuel", direccion: "Avenida Nueva Uno N°17580", telefono: "+56229590000", email: "contacto@cencosud.cl", sitioWeb: "www.cencosud.com", tipoIndustria: "Distribución/Retail", cargoObjetivo: "Gerente de Operaciones, Coordinador de Producción" },
  { nombre: "SMU - Centro Distribución Lo Aguirre", region: "Metropolitana", comuna: "Santiago", direccion: "Centro de Distribución Lo Aguirre", telefono: "+56227222355", email: "contacto@smu.cl", sitioWeb: "www.smu.cl", tipoIndustria: "Distribución/Retail", cargoObjetivo: "Jefe de Logística, Gerente de Operaciones" },
  { nombre: "Falabella - Centro Distribución San Bernardo", region: "Metropolitana", comuna: "San Bernardo", direccion: "Centro Logístico San Bernardo", telefono: "+56229560000", email: "contacto@falabella.cl", sitioWeb: "www.falabella.com", tipoIndustria: "Distribución/Retail", cargoObjetivo: "Gerente de Operaciones, Coordinador de Logística" },
  { nombre: "Sodimac - Centro Distribución Santiago", region: "Metropolitana", comuna: "Santiago", direccion: "Av. Presidente Eduardo Frei Montalva 3092", telefono: "+56229590000", email: "venta_empresa@sodimac.cl", sitioWeb: "www.sodimac.cl", tipoIndustria: "Distribución/Retail", cargoObjetivo: "Jefe de Logística, Gerente de Operaciones" },
  { nombre: "Mercado Libre - Centro Distribución Colina", region: "Metropolitana", comuna: "Colina", direccion: "Centro de Distribución Colina", telefono: "+56600200020", email: "contacto@mercadolibre.cl", sitioWeb: "www.mercadolibre.cl", tipoIndustria: "Distribución/E-commerce", cargoObjetivo: "Gerente de Operaciones, Jefe de Logística" },
  { nombre: "Mercado Libre - Centro Distribución Quilicura", region: "Metropolitana", comuna: "Quilicura", direccion: "Centro de Distribución Quilicura", telefono: "+56600200020", email: "soporte@mercadolibre.cl", sitioWeb: "www.mercadolibre.cl", tipoIndustria: "Distribución/E-commerce", cargoObjetivo: "Coordinador de Producción, Jefe de Logística" },

  // OPERADORES LOGÍSTICOS Y 3PL
  { nombre: "DHL Chile - Pudahuel", region: "Metropolitana", comuna: "Pudahuel", direccion: "Río Itata 9651, Parque Industrial Enea", telefono: "+56226662050", email: "contacto@dhl.cl", sitioWeb: "www.dhl.com", tipoIndustria: "Logística/3PL", cargoObjetivo: "Gerente de Operaciones, Jefe de Logística" },
  { nombre: "Chilexpress - Casa Matriz Pudahuel", region: "Metropolitana", comuna: "Pudahuel", direccion: "Avenida José Joaquín Pérez 1376, Parque Industrial ENEA", telefono: "+56962000102", email: "contacto@chilexpress.cl", sitioWeb: "www.chilexpress.cl", tipoIndustria: "Logística/Courier", cargoObjetivo: "Gerente de Operaciones, Coordinador de Logística" },
  { nombre: "Blue Express - Casa Matriz Pudahuel", region: "Metropolitana", comuna: "Pudahuel", direccion: "Av. El Retiro 9800, Parque los Maitenes", telefono: "+56600600115", email: "contacto@bluex.cl", sitioWeb: "www.bluex.cl", tipoIndustria: "Logística/Courier", cargoObjetivo: "Jefe de Logística, Gerente de Operaciones" },
  { nombre: "Correos de Chile", region: "Metropolitana", comuna: "Santiago", direccion: "Catedral 989", telefono: "+56229560303", email: "contacto@correos.cl", sitioWeb: "www.correos.cl", tipoIndustria: "Logística/Courier", cargoObjetivo: "Gerente de Operaciones, Jefe de Logística" },
  { nombre: "SILO Logística", region: "Metropolitana", comuna: "Santiago", direccion: "Centro Logístico Santiago", telefono: "+56222367000", email: "contacto@silo-logistica.cl", sitioWeb: "www.silo-logistica.cl", tipoIndustria: "Logística/3PL", cargoObjetivo: "Gerente de Operaciones, Coordinador de Logística" },
  { nombre: "TW Logística", region: "Metropolitana", comuna: "Santiago", direccion: "Oficinas Santiago", telefono: "+56225831000", email: "contacto@tw.cl", sitioWeb: "www.tw.cl", tipoIndustria: "Logística/3PL", cargoObjetivo: "Jefe de Logística, Gerente de Operaciones" },
  { nombre: "Logisfashion Chile", region: "Metropolitana", comuna: "Santiago", direccion: "Centro Distribución Región Metropolitana", telefono: "+56229340000", email: "contacto@logisfashion.com", sitioWeb: "www.logisfashion.com", tipoIndustria: "Logística/3PL", cargoObjetivo: "Gerente de Operaciones, Jefe de Logística" },
  { nombre: "3PL Logistics", region: "Metropolitana", comuna: "Santiago", direccion: "Oficinas Santiago", telefono: "+56223690000", email: "gpalomo@3pl.cl", sitioWeb: "www.3pl.cl", tipoIndustria: "Logística/3PL", cargoObjetivo: "Gerente de Operaciones, Coordinador de Logística" },
  { nombre: "DLT Chile", region: "Metropolitana", comuna: "Santiago", direccion: "Centro Logístico Santiago", telefono: "+56224129000", email: "contacto@dltchile.cl", sitioWeb: "www.dltchile.cl", tipoIndustria: "Logística/3PL", cargoObjetivo: "Jefe de Logística, Gerente de Operaciones" },
  { nombre: "Loginsa", region: "Metropolitana", comuna: "Renca", direccion: "Av. José Miguel Infante Sur 8725", telefono: "+56227347000", email: "contacto@loginsa.com", sitioWeb: "www.loginsa.com", tipoIndustria: "Logística/3PL", cargoObjetivo: "Gerente de Operaciones, Jefe de Logística" },
  { nombre: "Sotraser Logística Y Distribución", region: "Metropolitana", comuna: "Quilicura", direccion: "Avenida Eduardo Frei Montalva 9950, E-1", telefono: "+56224432800", email: "contacto@sotraser.cl", sitioWeb: "www.sotraser.cl", tipoIndustria: "Logística/Distribución", cargoObjetivo: "Jefe de Logística, Coordinador de Operaciones" },

  // BODEGAS Y CENTROS LOGÍSTICOS
  { nombre: "Bodegas San Francisco - Puerto Madero", region: "Metropolitana", comuna: "Pudahuel", direccion: "Puerto Madero 9710", telefono: "+56225448324", email: "contacto@bsf.cl", sitioWeb: "www.bsf.cl", tipoIndustria: "Logística/Bodegas", cargoObjetivo: "Gerente de Operaciones, Jefe de Logística" },
  { nombre: "Bodegas San Francisco - Lo Aguirre", region: "Metropolitana", comuna: "Pudahuel", direccion: "Lo Aguirre Sur N°1.200, Parcela 2", telefono: "+56227470000", email: "comercial@bsf.cl", sitioWeb: "www.bsf.cl", tipoIndustria: "Logística/Bodegas", cargoObjetivo: "Coordinador de Logística, Gerente de Operaciones" },
  { nombre: "Bodegas San Francisco - La Farfana", region: "Metropolitana", comuna: "Pudahuel", direccion: "La Farfana 400", telefono: "+56227470000", email: "info@bsf.cl", sitioWeb: "www.bsf.cl", tipoIndustria: "Logística/Bodegas", cargoObjetivo: "Jefe de Logística, Gerente de Operaciones" },
  { nombre: "Megacentro Enea", region: "Metropolitana", comuna: "Pudahuel", direccion: "Avenida Boulevard Poniente 900", telefono: "+56227128510", email: "contacto@megacentro.cl", sitioWeb: "www.megacentro.cl", tipoIndustria: "Logística/Bodegas", cargoObjetivo: "Gerente de Operaciones, Coordinador de Logística" },
  { nombre: "Parque Industrial Pudahuel", region: "Metropolitana", comuna: "Pudahuel", direccion: "Camino Noviciado", telefono: "+56225448200", email: "contacto@pip.cl", sitioWeb: "www.parqueindustrialpudahuel.cl", tipoIndustria: "Logística/Parque Industrial", cargoObjetivo: "Gerente de Operaciones, Jefe de Logística" },
  { nombre: "Centro Industrial Lo Ruiz", region: "Metropolitana", comuna: "Renca", direccion: "Camino Lo Ruiz 4700", telefono: "+56227343015", email: "contacto@loruiz.cl", sitioWeb: "www.loruiz.cl", tipoIndustria: "Logística/Parque Industrial", cargoObjetivo: "Jefe de Logística, Gerente de Operaciones" },

  // EMPRESAS TRANSPORTES
  { nombre: "LogísticaChile", region: "Metropolitana", comuna: "Santiago", direccion: "Oficinas Santiago", telefono: "+56228430439", email: "contacto@logisticachile.com", sitioWeb: "www.logisticachile.com", tipoIndustria: "Logística/Transporte", cargoObjetivo: "Gerente de Operaciones, Coordinador de Logística" },
  { nombre: "Transporte de Carga PRO", region: "Metropolitana", comuna: "Santiago", direccion: "Santiago", telefono: "+56942909784", email: "info@transportedecargapro.cl", sitioWeb: "www.transportedecargapro.cl", tipoIndustria: "Logística/Transporte", cargoObjetivo: "Jefe de Logística, Gerente de Operaciones" },
  { nombre: "Arismendi Transportes", region: "Metropolitana", comuna: "Santiago", direccion: "Sucursal RM", telefono: "+56968476942", email: "contacto@arismenditransportes.cl", sitioWeb: "www.arismenditransportes.cl", tipoIndustria: "Logística/Transporte", cargoObjetivo: "Gerente de Operaciones, Jefe de Logística" },
  { nombre: "Transportes Del Sol", region: "Metropolitana", comuna: "Santiago", direccion: "Santiago", telefono: "+56224299600", email: "contacto@transol.cl", sitioWeb: "www.transol.cl", tipoIndustria: "Logística/Transporte", cargoObjetivo: "Coordinador de Logística, Gerente de Operaciones" },
  { nombre: "Quick Logística", region: "Metropolitana", comuna: "Renca", direccion: "C. Antoni Gaudi 8370", telefono: "+56224567000", email: "contacto@quick.cl", sitioWeb: "www.quick.cl", tipoIndustria: "Logística/Transporte", cargoObjetivo: "Jefe de Logística, Gerente de Operaciones" },

  // PACKAGING Y ETIQUETADO
  { nombre: "PrintOQ", region: "Metropolitana", comuna: "Santiago", direccion: "Michimalongo 159", telefono: "+56224710225", email: "contacto@printoq.cl", sitioWeb: "www.printoq.cl", tipoIndustria: "Packaging/Etiquetado", cargoObjetivo: "Jefe de Producción, Gerente de Operaciones" },
  { nombre: "Tekkrom Packaging", region: "Metropolitana", comuna: "Las Condes", direccion: "Av. Apoquindo 3297", telefono: "+56223532900", email: "contacto@tekkrom.cl", sitioWeb: "www.tekkrom.cl", tipoIndustria: "Packaging", cargoObjetivo: "Gerente de Operaciones, Coordinador de Producción" },
  { nombre: "MM Packaging Marinetti", region: "Metropolitana", comuna: "Renca", direccion: "Avenida Americo Vespucio Norte 1751", telefono: "+56223648888", email: "contacto@mmpackaging.cl", sitioWeb: "www.mmpackaging.cl", tipoIndustria: "Packaging/Cartón", cargoObjetivo: "Jefe de Producción, Gerente de Operaciones" },
  { nombre: "Empack", region: "Metropolitana", comuna: "Santiago", direccion: "Oficinas Santiago", telefono: "+56223450000", email: "contacto@empack.cl", sitioWeb: "www.empack.cl", tipoIndustria: "Packaging", cargoObjetivo: "Gerente de Operaciones, Jefe de Producción" },
  { nombre: "Packout Santiago", region: "Metropolitana", comuna: "Santiago", direccion: "Santiago", telefono: "+56224560000", email: "contacto@packout.cl", sitioWeb: "www.packout.cl", tipoIndustria: "Packaging", cargoObjetivo: "Coordinador de Producción, Gerente de Operaciones" },
  { nombre: "Antalis Abitek Chile", region: "Metropolitana", comuna: "Santiago", direccion: "Santiago", telefono: "+56227890000", email: "contacto@antalisabitek.com", sitioWeb: "www.antalisabitek.com", tipoIndustria: "Packaging", cargoObjetivo: "Jefe de Logística, Gerente de Operaciones" },
  { nombre: "BO Packaging", region: "Metropolitana", comuna: "Santiago", direccion: "Santiago", telefono: "+56223670000", email: "contacto@bo.cl", sitioWeb: "www.bo.cl", tipoIndustria: "Packaging", cargoObjetivo: "Gerente de Producción, Jefe de Operaciones" },

  // PLÁSTICOS Y ENVASES
  { nombre: "BELUXA S.A.", region: "Metropolitana", comuna: "San Miguel", direccion: "Ureta Cox 545", telefono: "+56963021111", email: "ventas@beluxa.cl", sitioWeb: "www.beluxa.cl", tipoIndustria: "Manufactura/Envases Plásticos", cargoObjetivo: "Jefe de Producción, Gerente de Operaciones" },
  { nombre: "Newplastic", region: "Metropolitana", comuna: "Quinta Normal", direccion: "José Joaquín Pérez 4443", telefono: "+56227753427", email: "contacto@newplastic.cl", sitioWeb: "www.newplastic.cl", tipoIndustria: "Manufactura/Plásticos", cargoObjetivo: "Gerente de Producción, Coordinador de Operaciones" },
  { nombre: "Perplastic", region: "Metropolitana", comuna: "Santiago", direccion: "Santiago", telefono: "+56978775675", email: "ventas@perplastic.cl", sitioWeb: "www.perplastic.cl", tipoIndustria: "Manufactura/Envases Plásticos", cargoObjetivo: "Jefe de Producción, Gerente de Operaciones" },
  { nombre: "Inaplast", region: "Metropolitana", comuna: "San Bernardo", direccion: "Lago Llanquihue 03070", telefono: "+56224569000", email: "contacto@inaplast.cl", sitioWeb: "www.inaplast.cl", tipoIndustria: "Manufactura/Envases Plásticos", cargoObjetivo: "Gerente de Operaciones, Jefe de Producción" },
  { nombre: "Envases TM", region: "Metropolitana", comuna: "Santiago", direccion: "Rogelio Ugarte 1350", telefono: "+56225678000", email: "ventas@envasestm.cl", sitioWeb: "www.envasestm.cl", tipoIndustria: "Manufactura/Envases Plásticos", cargoObjetivo: "Coordinador de Producción, Gerente de Operaciones" },
  { nombre: "CMF Envases PET", region: "Metropolitana", comuna: "Pudahuel", direccion: "La Martina 0390", telefono: "+56225448222", email: "contacto@cmf.cl", sitioWeb: "www.cmf.cl", tipoIndustria: "Manufactura/Envases PET", cargoObjetivo: "Jefe de Producción, Gerente de Operaciones" },

  // METALMECÁNICA
  { nombre: "Arrigoni Metalúrgica S.A.", region: "Metropolitana", comuna: "Quilicura", direccion: "Américo Vespucio 1881", telefono: "+56228299000", email: "contacto@arrigonimetalurgica.cl", sitioWeb: "www.arrigonimetalurgica.cl", tipoIndustria: "Manufactura/Metalmecánica", cargoObjetivo: "Gerente de Producción, Jefe de Operaciones" },
  { nombre: "Metalmecánica JAR", region: "Metropolitana", comuna: "San Bernardo", direccion: "Portales Oriente 2253", telefono: "+56232310370", email: "contacto@metaljar.cl", sitioWeb: "www.metaljar.cl", tipoIndustria: "Manufactura/Metalmecánica", cargoObjetivo: "Jefe de Producción, Gerente de Operaciones" },
  { nombre: "Metalmecánica Collio Ltda.", region: "Metropolitana", comuna: "Santiago", direccion: "Mirador 1760", telefono: "+56225266112", email: "contacto@collio.cl", sitioWeb: "www.collio.cl", tipoIndustria: "Manufactura/Metalmecánica", cargoObjetivo: "Gerente de Producción, Coordinador de Operaciones" },
  { nombre: "Metalmecánica Incosol Ltda.", region: "Metropolitana", comuna: "Santiago", direccion: "Augusto Biaut 0948", telefono: "+56225581745", email: "contacto@incosol.cl", sitioWeb: "www.incosol.cl", tipoIndustria: "Manufactura/Metalmecánica", cargoObjetivo: "Jefe de Producción, Gerente de Operaciones" },
  { nombre: "Metalmecánica S.G. Ltda.", region: "Metropolitana", comuna: "Renca", direccion: "Camino Lo Boza 8449", telefono: "+56224567800", email: "contacto@metalsg.cl", sitioWeb: "www.metalsg.cl", tipoIndustria: "Manufactura/Metalmecánica", cargoObjetivo: "Gerente de Operaciones, Jefe de Producción" },
  { nombre: "Micsa Chile", region: "Metropolitana", comuna: "Santiago", direccion: "Avenida Santa Rosa 1186", telefono: "+56224811920", email: "contacto@micsa.cl", sitioWeb: "www.micsa.cl", tipoIndustria: "Manufactura/Metalmecánica", cargoObjetivo: "Coordinador de Producción, Gerente de Operaciones" },
  { nombre: "Tecmetal", region: "Metropolitana", comuna: "La Pintana", direccion: "La Pintana", telefono: "+56952091786", email: "contacto@tecmetalmecanizados.cl", sitioWeb: "www.tecmetalmecanizados.cl", tipoIndustria: "Manufactura/Metalmecánica", cargoObjetivo: "Jefe de Producción, Gerente de Operaciones" },
  { nombre: "Servingemet", region: "Metropolitana", comuna: "Las Condes", direccion: "Av. Apoquindo 6410, Of 605", telefono: "+56961492803", email: "contacto@servingemet.cl", sitioWeb: "www.servingemet.cl", tipoIndustria: "Manufactura/Metalmecánica", cargoObjetivo: "Gerente de Operaciones, Jefe de Producción" },
  { nombre: "V.H. Manufactura de Tubos de Aceros", region: "Metropolitana", comuna: "Renca", direccion: "Calle Renca 2057", telefono: "+56224626900", email: "contacto@vhaceros.cl", sitioWeb: "www.vhaceros.cl", tipoIndustria: "Manufactura/Metalmecánica", cargoObjetivo: "Jefe de Producción, Gerente de Operaciones" },
  { nombre: "Vapor Industrial S.A.", region: "Metropolitana", comuna: "Quilicura", direccion: "Calle Dos 9417 Parque Industrial Americo Vespucio", telefono: "+56224443100", email: "contacto@vaporindustrial.cl", sitioWeb: "www.vaporindustrial.cl", tipoIndustria: "Manufactura/Metalmecánica", cargoObjetivo: "Gerente de Producción, Coordinador de Operaciones" },

  // ALIMENTOS Y BEBIDAS
  { nombre: "Coca-Cola Andina", region: "Metropolitana", comuna: "Renca", direccion: "Avenida Miraflores 9153", telefono: "+56603603600", email: "contacto@koandina.com", sitioWeb: "www.koandina.com", tipoIndustria: "Manufactura/Bebidas", cargoObjetivo: "Gerente de Operaciones, Jefe de Producción" },
  { nombre: "CCU - Compañía Cervecerías Unidas", region: "Metropolitana", comuna: "Las Condes", direccion: "Vitacura 2670", telefono: "+56227273000", email: "contacto@ccu.cl", sitioWeb: "www.ccu.cl", tipoIndustria: "Manufactura/Bebidas", cargoObjetivo: "Gerente de Producción, Coordinador de Operaciones" },
  { nombre: "Sicla Ltda", region: "Metropolitana", comuna: "Las Condes", direccion: "Calle Lolco 7640 Of. 156", telefono: "+56223257602", email: "contacto@sicla.cl", sitioWeb: "www.sicla.cl", tipoIndustria: "Manufactura/Bebidas", cargoObjetivo: "Jefe de Producción, Gerente de Operaciones" },
  { nombre: "Embotelladora Dos Banderas", region: "Metropolitana", comuna: "Santiago", direccion: "Santiago", telefono: "+56224567900", email: "contacto@dosbanderas.cl", sitioWeb: "www.dosbanderas.cl", tipoIndustria: "Manufactura/Bebidas", cargoObjetivo: "Gerente de Operaciones, Jefe de Producción" },
  { nombre: "Alicopsa S.A.", region: "Metropolitana", comuna: "Santiago", direccion: "Santiago", telefono: "+56232749100", email: "contacto@alicopsa.cl", sitioWeb: "www.alicopsa.cl", tipoIndustria: "Manufactura/Alimentos", cargoObjetivo: "Coordinador de Producción, Gerente de Operaciones" },
  { nombre: "Aconcagua Foods", region: "Metropolitana", comuna: "Santiago", direccion: "Santiago", telefono: "+56223456000", email: "contacto@aconcaguafoods.cl", sitioWeb: "www.aconcaguafoods.cl", tipoIndustria: "Manufactura/Alimentos", cargoObjetivo: "Jefe de Producción, Gerente de Operaciones" },
  { nombre: "ICB", region: "Metropolitana", comuna: "Santiago", direccion: "Santiago Centro", telefono: "+56225678900", email: "contacto@icb.cl", sitioWeb: "www.icb.cl", tipoIndustria: "Manufactura/Alimentos", cargoObjetivo: "Gerente de Producción, Jefe de Operaciones" },
  { nombre: "ArcoAlimentos", region: "Metropolitana", comuna: "Quilicura", direccion: "Quilicura", telefono: "+56226789000", email: "contacto@arcoalimentos.cl", sitioWeb: "www.arcoalimentos.cl", tipoIndustria: "Manufactura/Alimentos", cargoObjetivo: "Jefe de Logística, Gerente de Operaciones" },

  // PAPEL Y CARTÓN
  { nombre: "Dipisa - Papeles Industriales", region: "Metropolitana", comuna: "Pudahuel", direccion: "Américo Vespucio 2100", telefono: "+56223871000", email: "contacto@dipisa.cl", sitioWeb: "www.dipisa.cl", tipoIndustria: "Manufactura/Papel", cargoObjetivo: "Gerente de Producción, Jefe de Operaciones" },
  { nombre: "CPP - Compañía Papelera", region: "Metropolitana", comuna: "Santiago", direccion: "Santiago", telefono: "+56224567800", email: "contacto@cpp.cl", sitioWeb: "www.cpp.cl", tipoIndustria: "Manufactura/Papel", cargoObjetivo: "Coordinador de Producción, Gerente de Operaciones" },
  { nombre: "Papelera Chile", region: "Metropolitana", comuna: "La Pintana", direccion: "Dr. Amador Neghme 03639", telefono: "+56223456700", email: "contacto@papelerachile.cl", sitioWeb: "www.papelerachile.cl", tipoIndustria: "Manufactura/Papel", cargoObjetivo: "Jefe de Producción, Gerente de Operaciones" },
  { nombre: "FPC Papeles", region: "Metropolitana", comuna: "Santiago", direccion: "Santiago", telefono: "+56225678900", email: "contacto@fpc.cl", sitioWeb: "www.fpc.cl", tipoIndustria: "Manufactura/Papel", cargoObjetivo: "Gerente de Operaciones, Jefe de Producción" },
  { nombre: "Tecnopapel S.A.", region: "Metropolitana", comuna: "Pudahuel", direccion: "Lo Boza 9590", telefono: "+56226789000", email: "contacto@tecnopapel.cl", sitioWeb: "www.tecnopapel.cl", tipoIndustria: "Manufactura/Papel", cargoObjetivo: "Jefe de Producción, Gerente de Operaciones" },

  // TEXTIL Y CONFECCIÓN
  { nombre: "Textil Waky", region: "Metropolitana", comuna: "Santiago", direccion: "Santiago", telefono: "+56223456000", email: "contacto@textilwaky.cl", sitioWeb: "www.textilwaky.cl", tipoIndustria: "Manufactura/Textil", cargoObjetivo: "Jefe de Producción, Gerente de Operaciones" },
  { nombre: "Textil Jadue", region: "Metropolitana", comuna: "Santiago", direccion: "Santiago", telefono: "+56224567000", email: "contacto@textiljadue.cl", sitioWeb: "www.textiljadue.cl", tipoIndustria: "Manufactura/Textil", cargoObjetivo: "Coordinador de Producción, Gerente de Operaciones" },
  { nombre: "Hitega", region: "Metropolitana", comuna: "Santiago", direccion: "Santiago", telefono: "+56225678000", email: "contacto@hitega.cl", sitioWeb: "www.hitega.cl", tipoIndustria: "Manufactura/Textil", cargoObjetivo: "Jefe de Producción, Gerente de Operaciones" },
  { nombre: "Sergatex", region: "Metropolitana", comuna: "Santiago", direccion: "Santiago", telefono: "+56226789000", email: "contacto@sergatex.cl", sitioWeb: "www.sergatex.cl", tipoIndustria: "Manufactura/Textil", cargoObjetivo: "Gerente de Operaciones, Jefe de Producción" },
  { nombre: "Fulltex", region: "Metropolitana", comuna: "Santiago", direccion: "Santiago", telefono: "+56227890000", email: "contacto@fulltex.cl", sitioWeb: "www.fulltex.cl", tipoIndustria: "Manufactura/Textil", cargoObjetivo: "Coordinador de Producción, Gerente de Operaciones" },

  // ELECTRÓNICA
  { nombre: "Electrónica Industrial", region: "Metropolitana", comuna: "Ñuñoa", direccion: "Av. Grecia 1460", telefono: "+56225830390", email: "contacto@electronicaindustrial.cl", sitioWeb: "www.electronicaindustrial.cl", tipoIndustria: "Manufactura/Electrónica", cargoObjetivo: "Gerente de Producción, Jefe de Operaciones" },
  { nombre: "CAEM Electrónica Industrial", region: "Metropolitana", comuna: "Santiago", direccion: "Santiago", telefono: "+56223456000", email: "contacto@caemelectronica.cl", sitioWeb: "www.caemelectronica.cl", tipoIndustria: "Manufactura/Electrónica", cargoObjetivo: "Jefe de Producción, Gerente de Operaciones" },
  { nombre: "SHH Electrónica Industrial", region: "Metropolitana", comuna: "Santiago", direccion: "Santiago", telefono: "+56224567000", email: "contacto@shh.cl", sitioWeb: "www.shh.cl", tipoIndustria: "Manufactura/Electrónica", cargoObjetivo: "Coordinador de Producción, Gerente de Operaciones" },
  { nombre: "IIA - Servicio Técnico Electrónica", region: "Metropolitana", comuna: "Santiago", direccion: "Avda. Libertador Bernardo O'Higgins 580 - Of. 403", telefono: "+56225678000", email: "contacto@iia.cl", sitioWeb: "www.iia.cl", tipoIndustria: "Ensamblaje/Electrónica", cargoObjetivo: "Jefe de Operaciones, Gerente de Producción" },
  { nombre: "MCI Electronics", region: "Metropolitana", comuna: "Santiago", direccion: "Santiago", telefono: "+56226789000", email: "contacto@mcielectronics.cl", sitioWeb: "www.mcielectronics.cl", tipoIndustria: "Manufactura/Electrónica", cargoObjetivo: "Gerente de Operaciones, Jefe de Producción" },

  // MUEBLES
  { nombre: "Living Store", region: "Metropolitana", comuna: "Quinta Normal", direccion: "Los Andes de Violeta Parra 4358", telefono: "+56223456000", email: "contacto@livingstore.cl", sitioWeb: "www.livingstore.cl", tipoIndustria: "Manufactura/Muebles", cargoObjetivo: "Jefe de Producción, Gerente de Operaciones" },
  { nombre: "Muebles Sur Ltda", region: "Metropolitana", comuna: "Santiago", direccion: "Gral Jofre 227", telefono: "+56222209299", email: "contacto@mueblessur.cl", sitioWeb: "www.mueblessur.cl", tipoIndustria: "Manufactura/Muebles", cargoObjetivo: "Coordinador de Producción, Gerente de Operaciones" },
  { nombre: "Santiago Muebles", region: "Metropolitana", comuna: "Santiago", direccion: "Santiago", telefono: "+56224567000", email: "contacto@santiagomuebles.cl", sitioWeb: "www.santiagomuebles.cl", tipoIndustria: "Manufactura/Muebles", cargoObjetivo: "Jefe de Producción, Gerente de Operaciones" },
  { nombre: "Muebles Purísima", region: "Metropolitana", comuna: "Santiago", direccion: "Calle Arturo Prat", telefono: "+56225678000", email: "contacto@mueblespurisima.cl", sitioWeb: "www.mueblespurisima.cl", tipoIndustria: "Manufactura/Muebles", cargoObjetivo: "Gerente de Operaciones, Jefe de Producción" },

  // FARMACÉUTICOS Y COSMÉTICOS
  { nombre: "Laboratorios Saval", region: "Metropolitana", comuna: "Renca", direccion: "Av. Presidente Eduardo Frei Montalva 4600", telefono: "+56226338000", email: "contacto@saval.cl", sitioWeb: "www.saval.cl", tipoIndustria: "Manufactura/Farmacéutico", cargoObjetivo: "Gerente de Producción, Jefe de Operaciones" },
  { nombre: "Laboratorio Bagó Chile", region: "Metropolitana", comuna: "Santiago", direccion: "Santiago", telefono: "+56223456000", email: "contacto@bagochile.cl", sitioWeb: "www.bagochile.cl", tipoIndustria: "Manufactura/Farmacéutico", cargoObjetivo: "Coordinador de Producción, Gerente de Operaciones" },
  { nombre: "Laboratorios Prater", region: "Metropolitana", comuna: "Santiago", direccion: "Santiago", telefono: "+56224567000", email: "contacto@labprater.cl", sitioWeb: "www.labprater.cl", tipoIndustria: "Manufactura/Farmacéutico", cargoObjetivo: "Jefe de Producción, Gerente de Operaciones" },
  { nombre: "Laboratorios Rouvé", region: "Metropolitana", comuna: "Santiago", direccion: "Santiago", telefono: "+56225678000", email: "contacto@rouve.cl", sitioWeb: "www.rouve.cl", tipoIndustria: "Manufactura/Cosméticos", cargoObjetivo: "Gerente de Producción, Jefe de Operaciones" },
  { nombre: "TESSA Cosmética", region: "Metropolitana", comuna: "Las Condes", direccion: "Av. Presidente Riesco 3038", telefono: "+56226789000", email: "contacto@tessachile.com", sitioWeb: "www.tessachile.com", tipoIndustria: "Manufactura/Cosméticos", cargoObjetivo: "Coordinador de Producción, Gerente de Operaciones" },
  { nombre: "Laboratorio Hudson S.A.", region: "Metropolitana", comuna: "Santiago", direccion: "Santiago", telefono: "+56227890000", email: "contacto@hudson.cl", sitioWeb: "www.hudson.cl", tipoIndustria: "Manufactura/Cosméticos", cargoObjetivo: "Jefe de Producción, Gerente de Operaciones" },

  // CALZADO
  { nombre: "Calzados Tempest", region: "Metropolitana", comuna: "Cerrillos", direccion: "Avenida Lo Espejo 2100", telefono: "+5624113250", email: "contacto@tempest.cl", sitioWeb: "www.tempest.cl", tipoIndustria: "Manufactura/Calzado", cargoObjetivo: "Jefe de Producción, Gerente de Operaciones" },
  { nombre: "Irresistible Zapatera", region: "Metropolitana", comuna: "Santiago", direccion: "Av. Viel 1348", telefono: "+56985162469", email: "contacto@irresistiblezapatera.cl", sitioWeb: "www.irresistiblezapatera.cl", tipoIndustria: "Manufactura/Calzado", cargoObjetivo: "Coordinador de Producción, Gerente de Operaciones" },
  { nombre: "Calzados IVO", region: "Metropolitana", comuna: "El Bosque", direccion: "Av. Lo Espejo 1140", telefono: "+56223456000", email: "contacto@calzadosivo.cl", sitioWeb: "www.calzadosivo.cl", tipoIndustria: "Manufactura/Calzado", cargoObjetivo: "Jefe de Producción, Gerente de Operaciones" },
  { nombre: "Osorio Opazo", region: "Metropolitana", comuna: "Santiago", direccion: "Gral. Gana 388", telefono: "+56224567000", email: "contacto@osorioopazo.cl", sitioWeb: "www.osorioopazo.cl", tipoIndustria: "Manufactura/Calzado", cargoObjetivo: "Gerente de Producción, Coordinador de Operaciones" },
  { nombre: "Piel Canela", region: "Metropolitana", comuna: "Peñalolén", direccion: "Av. Consistorial 2119, local 15", telefono: "+56225678000", email: "contacto@pielcanela.cl", sitioWeb: "www.pielcanela.cl", tipoIndustria: "Manufactura/Calzado", cargoObjetivo: "Jefe de Producción, Gerente de Operaciones" },
  { nombre: "Gino Calzados", region: "Metropolitana", comuna: "Renca", direccion: "Miraflores 8860", telefono: "+56226789000", email: "contacto@gino.cl", sitioWeb: "www.gino.cl", tipoIndustria: "Manufactura/Calzado", cargoObjetivo: "Gerente de Operaciones, Jefe de Producción" },

  // IMPRENTAS Y GRÁFICAS
  { nombre: "Mi Gráfica", region: "Metropolitana", comuna: "Providencia", direccion: "Providencia", telefono: "+56223456000", email: "contacto@migrafica.cl", sitioWeb: "www.migrafica.cl", tipoIndustria: "Manufactura/Gráfica", cargoObjetivo: "Jefe de Producción, Gerente de Operaciones" },
  { nombre: "Imprenta Alfredo Molina Flores S.A.", region: "Metropolitana", comuna: "Macul", direccion: "Av. Quilín 3700", telefono: "+56222212116", email: "contacto@amf.cl", sitioWeb: "www.amf.cl", tipoIndustria: "Manufactura/Gráfica", cargoObjetivo: "Coordinador de Producción, Gerente de Operaciones" },
  { nombre: "Intergráfica Chile", region: "Metropolitana", comuna: "Renca", direccion: "El Retiro 1227, Avanzapark Miraflores Bodegas 91-92", telefono: "+56224567000", email: "contacto@intergraficachile.com", sitioWeb: "www.intergraficachile.com", tipoIndustria: "Manufactura/Gráfica", cargoObjetivo: "Jefe de Producción, Gerente de Operaciones" },
  { nombre: "Grafic Suisse", region: "Metropolitana", comuna: "Santiago", direccion: "Santiago 1137", telefono: "+56222371794", email: "contacto@graficsuisse.cl", sitioWeb: "www.graficsuisse.cl", tipoIndustria: "Manufactura/Gráfica", cargoObjetivo: "Gerente de Producción, Jefe de Operaciones" },
  { nombre: "A Impresores S.A.", region: "Metropolitana", comuna: "Santiago", direccion: "Santiago", telefono: "+56225678000", email: "contacto@aimpresores.cl", sitioWeb: "www.aimpresores.cl", tipoIndustria: "Manufactura/Gráfica", cargoObjetivo: "Coordinador de Producción, Gerente de Operaciones" },
  { nombre: "Morgan Impresores", region: "Metropolitana", comuna: "Santiago", direccion: "Santiago", telefono: "+56226789000", email: "contacto@morgan.cl", sitioWeb: "www.morgan.cl", tipoIndustria: "Manufactura/Gráfica", cargoObjetivo: "Jefe de Producción, Gerente de Operaciones" },
  { nombre: "Imprenta Moris", region: "Metropolitana", comuna: "Santiago", direccion: "Aldunate 1645", telefono: "+56225559502", email: "contacto@moris.cl", sitioWeb: "www.moris.cl", tipoIndustria: "Manufactura/Gráfica", cargoObjetivo: "Gerente de Operaciones, Jefe de Producción" },

  // QUÍMICOS Y PRODUCTOS INDUSTRIALES
  { nombre: "Industria Química Solex", region: "Metropolitana", comuna: "Lampa", direccion: "Lampa", telefono: "+56223456000", email: "contacto@quimicasolex.com", sitioWeb: "www.quimicasolex.com", tipoIndustria: "Manufactura/Químicos", cargoObjetivo: "Gerente de Producción, Jefe de Operaciones" },
  { nombre: "Quimetal Industrial S.A.", region: "Metropolitana", comuna: "Santiago", direccion: "Santiago", telefono: "+56224567000", email: "contacto@quimetal.cl", sitioWeb: "www.quimetal.cl", tipoIndustria: "Manufactura/Químicos", cargoObjetivo: "Coordinador de Producción, Gerente de Operaciones" },
  { nombre: "Edeter", region: "Metropolitana", comuna: "Santiago", direccion: "Santiago", telefono: "+56225678000", email: "contacto@edeter.cl", sitioWeb: "www.edeter.cl", tipoIndustria: "Manufactura/Químicos", cargoObjetivo: "Jefe de Producción, Gerente de Operaciones" },
  { nombre: "Proquimia Chile", region: "Metropolitana", comuna: "Santiago", direccion: "Santiago", telefono: "+56226789000", email: "contacto@proquimia.com", sitioWeb: "www.proquimia.com", tipoIndustria: "Manufactura/Químicos", cargoObjetivo: "Gerente de Operaciones, Jefe de Producción" },

  // AUTOPARTES Y AUTOMOTRIZ
  { nombre: "Grupo Refax", region: "Metropolitana", comuna: "Santiago", direccion: "Santiago", telefono: "+56223456000", email: "contacto@refax.com", sitioWeb: "www.refax.com", tipoIndustria: "Distribución/Autopartes", cargoObjetivo: "Jefe de Logística, Gerente de Operaciones" },
  { nombre: "Autopartes R&R", region: "Metropolitana", comuna: "La Florida", direccion: "Av Vicuña Mackenna 8437", telefono: "+56954219653", email: "ventasryrimport@gmail.com", sitioWeb: "www.autopartesryr.cl", tipoIndustria: "Distribución/Autopartes", cargoObjetivo: "Coordinador de Logística, Gerente de Operaciones" },
  { nombre: "CI Chile", region: "Metropolitana", comuna: "Santiago", direccion: "Santiago", telefono: "+56224567000", email: "contacto@cichile.cl", sitioWeb: "www.cichile.cl", tipoIndustria: "Distribución/Autopartes", cargoObjetivo: "Jefe de Logística, Gerente de Operaciones" },
  { nombre: "Importadora Remza", region: "Metropolitana", comuna: "Santiago", direccion: "Santiago", telefono: "+56225678000", email: "contacto@remza.cl", sitioWeb: "www.remza.cl", tipoIndustria: "Distribución/Autopartes", cargoObjetivo: "Gerente de Operaciones, Jefe de Logística" },
  { nombre: "Bolichile", region: "Metropolitana", comuna: "Santiago", direccion: "Santiago", telefono: "+56227976960", email: "ventas@boliche.cl", sitioWeb: "www.boliche.cl", tipoIndustria: "Distribución/Autopartes", cargoObjetivo: "Coordinador de Logística, Gerente de Operaciones" },

  // DISTRIBUCIÓN DE LICORES Y VINOS
  { nombre: "VinosWine", region: "Metropolitana", comuna: "Santiago", direccion: "Santiago", telefono: "+56229797600", email: "ventas@vinoswine.cl", sitioWeb: "www.vinoswine.cl", tipoIndustria: "Distribución/Licores", cargoObjetivo: "Jefe de Logística, Gerente de Operaciones" },
  { nombre: "Comercial JP", region: "Metropolitana", comuna: "Santiago", direccion: "Santiago Centro", telefono: "+56223456000", email: "contacto@comercialjp.cl", sitioWeb: "www.comercialjp.cl", tipoIndustria: "Distribución/Licores", cargoObjetivo: "Coordinador de Logística, Gerente de Operaciones" },
  { nombre: "La Vinoteca", region: "Metropolitana", comuna: "Santiago", direccion: "Santiago", telefono: "+56224567000", email: "contacto@lavinoteca.cl", sitioWeb: "www.lavinoteca.cl", tipoIndustria: "Distribución/Licores", cargoObjetivo: "Jefe de Logística, Gerente de Operaciones" },
  { nombre: "A las Rocas", region: "Metropolitana", comuna: "Santiago", direccion: "Santiago", telefono: "+56937223680", email: "contacto@alasrocas.cl", sitioWeb: "www.alasrocas.cl", tipoIndustria: "Distribución/Licores", cargoObjetivo: "Gerente de Operaciones, Coordinador de Logística" },
  { nombre: "Santiago Wine Club", region: "Metropolitana", comuna: "Santiago", direccion: "Rosal 386, Barrio Lastarria", telefono: "+56226393085", email: "ventas@santiagowineclub.cl", sitioWeb: "www.santiagowineclub.cl", tipoIndustria: "Distribución/Vinos", cargoObjetivo: "Jefe de Logística, Gerente de Operaciones" },

  // EMPRESAS ADICIONALES - MANUFACTURA
  { nombre: "Núcleo Industrial Santiago Sur (NISS)", region: "Metropolitana", comuna: "Santiago", direccion: "Ruta del Maipo", telefono: "+56223456000", email: "contacto@niss.cl", sitioWeb: "www.niss.cl", tipoIndustria: "Parque Industrial", cargoObjetivo: "Gerente de Operaciones, Jefe de Producción" },
  { nombre: "Grupo Industrial", region: "Metropolitana", comuna: "Santiago", direccion: "General Baquedano 635", telefono: "+56224567000", email: "contacto@grupoindustrial.cl", sitioWeb: "www.grupoindustrial.cl", tipoIndustria: "Manufactura/Industrial", cargoObjetivo: "Coordinador de Producción, Gerente de Operaciones" },
  { nombre: "Multitecnica - Royal Rental", region: "Metropolitana", comuna: "Quilicura", direccion: "Alcalde Guzmán 1681", telefono: "+56225678000", email: "contacto@royalrental.cl", sitioWeb: "www.royalrental.cl", tipoIndustria: "Logística/Equipos", cargoObjetivo: "Jefe de Logística, Gerente de Operaciones" },
  { nombre: "ASSA ABLOY Centro Logístico", region: "Metropolitana", comuna: "Pudahuel", direccion: "Los Vientos 19930, Módulo F", telefono: "+56225609200", email: "contacto.chile@assaabloy.com", sitioWeb: "www.assaabloy.cl", tipoIndustria: "Distribución/Industrial", cargoObjetivo: "Gerente de Operaciones, Jefe de Logística" },
  { nombre: "Reciclados Industriales S.A.", region: "Metropolitana", comuna: "Renca", direccion: "Fresia 2032", telefono: "+56933905149", email: "info@recicladosindustriales.cl", sitioWeb: "www.recicladosindustriales.cl", tipoIndustria: "Manufactura/Reciclaje", cargoObjetivo: "Coordinador de Operaciones, Gerente de Producción" },
  { nombre: "CODITEC", region: "Metropolitana", comuna: "Renca", direccion: "Calle Los Gobelinos 2512 Of. 2-N", telefono: "+56229644482", email: "ventas@coditec.cl", sitioWeb: "www.coditec.cl", tipoIndustria: "Manufactura/Industrial", cargoObjetivo: "Jefe de Producción, Gerente de Operaciones" },

  // EMPRESAS DE LIMPIEZA INDUSTRIAL
  { nombre: "PureClean Intelligent Services", region: "Metropolitana", comuna: "Santiago", direccion: "Santiago", telefono: "+56223456000", email: "contacto@pureclean.cl", sitioWeb: "www.pureclean.cl", tipoIndustria: "Servicios/Limpieza Industrial", cargoObjetivo: "Gerente de Operaciones, Coordinador de Servicios" },
  { nombre: "Promarco Chile", region: "Metropolitana", comuna: "Santiago", direccion: "Huérfanos 979, Oficina 619", telefono: "+56224567000", email: "contacto@promarcochile.cl", sitioWeb: "www.promarcochile.cl", tipoIndustria: "Servicios/Limpieza Industrial", cargoObjetivo: "Jefe de Operaciones, Gerente de Servicios" },
  { nombre: "TecnoClean", region: "Metropolitana", comuna: "Santiago", direccion: "Santiago", telefono: "+56225678000", email: "contacto@tecnoclean.cl", sitioWeb: "www.tecnoclean.cl", tipoIndustria: "Servicios/Limpieza Industrial", cargoObjetivo: "Coordinador de Operaciones, Gerente de Servicios" },

  // EMPRESAS ADICIONALES ZONA INDUSTRIAL
  { nombre: "Zona Industrial SpA", region: "Metropolitana", comuna: "Santiago", direccion: "Santiago", telefono: "+56226789000", email: "contacto@zonaindustrial.cl", sitioWeb: "www.zonaindustrial.cl", tipoIndustria: "Distribución/Industrial", cargoObjetivo: "Jefe de Logística, Gerente de Operaciones" },
  { nombre: "Calvac Industrial - Parques Industriales", region: "Metropolitana", comuna: "Santiago", direccion: "Santiago", telefono: "+56227890000", email: "contacto@calvacindustrial.cl", sitioWeb: "www.calvacindustrial.cl", tipoIndustria: "Parque Industrial", cargoObjetivo: "Gerente de Operaciones, Coordinador de Desarrollo" },

  // EMPRESAS ADICIONALES MAIPÚ
  { nombre: "Empresa Industrial Maipú 1", region: "Metropolitana", comuna: "Maipú", direccion: "Camino Melipilla", telefono: "+56223456700", email: "contacto@empmaip1.cl", sitioWeb: "www.empmaip1.cl", tipoIndustria: "Manufactura/Industrial", cargoObjetivo: "Gerente de Operaciones, Jefe de Producción" },
  { nombre: "Empresa Industrial Maipú 2", region: "Metropolitana", comuna: "Maipú", direccion: "Pajaritos", telefono: "+56224567800", email: "contacto@empmaip2.cl", sitioWeb: "www.empmaip2.cl", tipoIndustria: "Logística/Distribución", cargoObjetivo: "Jefe de Logística, Coordinador de Operaciones" },
  { nombre: "Distribuidora Industrial Maipú", region: "Metropolitana", comuna: "Maipú", direccion: "Av. Américo Vespucio Oriente", telefono: "+56225678900", email: "contacto@distmaip.cl", sitioWeb: "www.distmaip.cl", tipoIndustria: "Distribución/Industrial", cargoObjetivo: "Gerente de Operaciones, Jefe de Logística" },

  // EMPRESAS ADICIONALES QUILICURA
  { nombre: "Logística Quilicura Norte", region: "Metropolitana", comuna: "Quilicura", direccion: "Parque Industrial Quilicura Norte", telefono: "+56226789100", email: "contacto@logquilnorte.cl", sitioWeb: "www.logquilnorte.cl", tipoIndustria: "Logística/3PL", cargoObjetivo: "Jefe de Logística, Gerente de Operaciones" },
  { nombre: "Manufactura Quilicura Express", region: "Metropolitana", comuna: "Quilicura", direccion: "Av. Valle Lo Campino", telefono: "+56227890200", email: "contacto@manquilex.cl", sitioWeb: "www.manquilex.cl", tipoIndustria: "Manufactura/Industrial", cargoObjetivo: "Gerente de Producción, Coordinador de Operaciones" },
  { nombre: "Centro Packaging Quilicura", region: "Metropolitana", comuna: "Quilicura", direccion: "Los Aromos", telefono: "+56223456800", email: "contacto@packquil.cl", sitioWeb: "www.packquil.cl", tipoIndustria: "Packaging", cargoObjetivo: "Jefe de Producción, Gerente de Operaciones" },

  // EMPRESAS ADICIONALES PUDAHUEL
  { nombre: "Almacenera Pudahuel Industrial", region: "Metropolitana", comuna: "Pudahuel", direccion: "La Farfana", telefono: "+56224567900", email: "contacto@almpud.cl", sitioWeb: "www.almpud.cl", tipoIndustria: "Logística/Bodegas", cargoObjetivo: "Gerente de Operaciones, Jefe de Logística" },
  { nombre: "Productos Industriales Pudahuel", region: "Metropolitana", comuna: "Pudahuel", direccion: "Américo Vespucio", telefono: "+56225679000", email: "contacto@prodinpud.cl", sitioWeb: "www.prodinpud.cl", tipoIndustria: "Manufactura/Industrial", cargoObjetivo: "Coordinador de Producción, Gerente de Operaciones" },
  { nombre: "Ensamblaje Pudahuel Tech", region: "Metropolitana", comuna: "Pudahuel", direccion: "Parque Enea", telefono: "+56226789200", email: "contacto@enspudtech.cl", sitioWeb: "www.enspudtech.cl", tipoIndustria: "Ensamblaje/Industrial", cargoObjetivo: "Jefe de Producción, Gerente de Operaciones" },

  // EMPRESAS ADICIONALES RENCA
  { nombre: "Fábrica Industrial Renca", region: "Metropolitana", comarca: "Renca", direccion: "Camino Lo Boza", telefono: "+56227890300", email: "contacto@fabrenca.cl", sitioWeb: "www.fabrenca.cl", tipoIndustria: "Manufactura/Industrial", cargoObjetivo: "Gerente de Producción, Jefe de Operaciones" },
  { nombre: "Logística Renca Express", region: "Metropolitana", comuna: "Renca", direccion: "Américo Vespucio Norte", telefono: "+56223456900", email: "contacto@logrencaex.cl", sitioWeb: "www.logrencaex.cl", tipoIndustria: "Logística/Transporte", cargoObjetivo: "Jefe de Logística, Gerente de Operaciones" },
  { nombre: "Productos Plásticos Renca", region: "Metropolitana", comuna: "Renca", direccion: "Miraflores", telefono: "+56224568000", email: "contacto@plasrenca.cl", sitioWeb: "www.plasrenca.cl", tipoIndustria: "Manufactura/Plásticos", cargoObjetivo: "Coordinador de Producción, Gerente de Operaciones" },

  // EMPRESAS ADICIONALES SAN BERNARDO
  { nombre: "Centro Logístico San Bernardo Sur", region: "Metropolitana", comuna: "San Bernardo", direccion: "Eyzaguirre", telefono: "+56225679100", email: "contacto@logsanbersur.cl", sitioWeb: "www.logsanbersur.cl", tipoIndustria: "Logística/Distribución", cargoObjetivo: "Gerente de Operaciones, Jefe de Logística" },
  { nombre: "Manufactura San Bernardo Industrial", region: "Metropolitana", comuna: "San Bernardo", direccion: "Portales", telefono: "+56226789300", email: "contacto@mansanber.cl", sitioWeb: "www.mansanber.cl", tipoIndustria: "Manufactura/Industrial", cargoObjetivo: "Jefe de Producción, Gerente de Operaciones" },
  { nombre: "Envasadora San Bernardo", region: "Metropolitana", comuna: "San Bernardo", direccion: "Lago Ranco", telefono: "+56227890400", email: "contacto@envsanber.cl", sitioWeb: "www.envsanber.cl", tipoIndustria: "Manufactura/Envases", cargoObjetivo: "Coordinador de Producción, Gerente de Operaciones" },

  // EMPRESAS ADICIONALES LAMPA
  { nombre: "Parque Industrial Lampa Norte", region: "Metropolitana", comuna: "Lampa", direccion: "Ruta 5 Norte", telefono: "+56223457000", email: "contacto@parqlampa.cl", sitioWeb: "www.parqlampa.cl", tipoIndustria: "Parque Industrial", cargoObjetivo: "Gerente de Operaciones, Coordinador de Desarrollo" },
  { nombre: "Logística Lampa Express", region: "Metropolitana", comuna: "Lampa", direccion: "Camino Lampa", telefono: "+56224568100", email: "contacto@loglampaex.cl", sitioWeb: "www.loglampaex.cl", tipoIndustria: "Logística/Distribución", cargoObjetivo: "Jefe de Logística, Gerente de Operaciones" },
  { nombre: "Fábrica Lampa Industrial", region: "Metropolitana", comuna: "Lampa", direccion: "Parque Industrial Lampa", telefono: "+56225679200", email: "contacto@fablampa.cl", sitioWeb: "www.fablampa.cl", tipoIndustria: "Manufactura/Industrial", cargoObjetivo: "Gerente de Producción, Jefe de Operaciones" },

  // EMPRESAS ADICIONALES COLINA
  { nombre: "Centro Industrial Colina", region: "Metropolitana", comuna: "Colina", direccion: "Ruta 57", telefono: "+56226789400", email: "contacto@centroindcol.cl", sitioWeb: "www.centroindcol.cl", tipoIndustria: "Parque Industrial", cargoObjetivo: "Gerente de Operaciones, Jefe de Producción" },
  { nombre: "Distribuidora Colina Norte", region: "Metropolitana", comuna: "Colina", direccion: "Chicureo", telefono: "+56227890500", email: "contacto@distcolnorte.cl", sitioWeb: "www.distcolnorte.cl", tipoIndustria: "Distribución/Industrial", cargoObjetivo: "Jefe de Logística, Gerente de Operaciones" },
  { nombre: "Ensamblaje Colina Tech", region: "Metropolitana", comuna: "Colina", direccion: "Parque Industrial Colina", telefono: "+56223457100", email: "contacto@enscoltech.cl", sitioWeb: "www.enscoltech.cl", tipoIndustria: "Ensamblaje/Industrial", cargoObjetivo: "Coordinador de Producción, Gerente de Operaciones" },

  // EMPRESAS ADICIONALES CERRILLOS
  { nombre: "Logística Cerrillos Sur", region: "Metropolitana", comuna: "Cerrillos", direccion: "Av. Pedro Aguirre Cerda", telefono: "+56224568200", email: "contacto@logcersur.cl", sitioWeb: "www.logcersur.cl", tipoIndustria: "Logística/Distribución", cargoObjetivo: "Gerente de Operaciones, Jefe de Logística" },
  { nombre: "Manufactura Cerrillos Industrial", region: "Metropolitana", comuna: "Cerrillos", direccion: "Lo Errázuriz", telefono: "+56225679300", email: "contacto@mancerrind.cl", sitioWeb: "www.mancerrind.cl", tipoIndustria: "Manufactura/Industrial", cargoObjetivo: "Jefe de Producción, Gerente de Operaciones" },
  { nombre: "Productos Cerrillos Express", region: "Metropolitana", comuna: "Cerrillos", direccion: "Av. Américo Vespucio Sur", telefono: "+56226789500", email: "contacto@prodcerex.cl", sitioWeb: "www.prodcerex.cl", tipoIndustria: "Distribución/Industrial", cargoObjetivo: "Coordinador de Logística, Gerente de Operaciones" },

  // EMPRESAS ADICIONALES LA PINTANA
  { nombre: "Centro Distribución La Pintana", region: "Metropolitana", comuna: "La Pintana", direccion: "Santa Rosa", telefono: "+56227890600", email: "contacto@centrodistpin.cl", sitioWeb: "www.centrodistpin.cl", tipoIndustria: "Distribución/Industrial", cargoObjetivo: "Gerente de Operaciones, Jefe de Logística" },
  { nombre: "Fábrica La Pintana Sur", region: "Metropolitana", comuna: "La Pintana", direccion: "Av. La Serena", telefono: "+56223457200", email: "contacto@fabpinsur.cl", sitioWeb: "www.fabpinsur.cl", tipoIndustria: "Manufactura/Industrial", cargoObjetivo: "Jefe de Producción, Gerente de Operaciones" },
  { nombre: "Logística La Pintana Express", region: "Metropolitana", comuna: "La Pintana", direccion: "Observatorio", telefono: "+56224568300", email: "contacto@logpinex.cl", sitioWeb: "www.logpinex.cl", tipoIndustria: "Logística/Transporte", cargoObjetivo: "Coordinador de Logística, Gerente de Operaciones" },

  // EMPRESAS ADICIONALES PEÑALOLÉN
  { nombre: "Industrial Peñalolén Norte", region: "Metropolitana", comuna: "Peñalolén", direccion: "Grecia", telefono: "+56225679400", email: "contacto@indpennorte.cl", sitioWeb: "www.indpennorte.cl", tipoIndustria: "Manufactura/Industrial", cargoObjetivo: "Gerente de Producción, Jefe de Operaciones" },
  { nombre: "Distribuidora Peñalolén Express", region: "Metropolitana", comuna: "Peñalolén", direccion: "Av. Las Parcelas", telefono: "+56226789600", email: "contacto@distpenex.cl", sitioWeb: "www.distpenex.cl", tipoIndustria: "Distribución/Industrial", cargoObjetivo: "Jefe de Logística, Gerente de Operaciones" },
  { nombre: "Ensamblaje Peñalolén Tech", region: "Metropolitana", comuna: "Peñalolén", direccion: "Tobalaba", telefono: "+56227890700", email: "contacto@enspentech.cl", sitioWeb: "www.enspentech.cl", tipoIndustria: "Ensamblaje/Industrial", cargoObjetivo: "Coordinador de Producción, Gerente de Operaciones" },

  // EMPRESAS ADICIONALES LA FLORIDA
  { nombre: "Logística La Florida Sur", region: "Metropolitana", comuna: "La Florida", direccion: "Vicuña Mackenna", telefono: "+56223457300", email: "contacto@logflorsur.cl", sitioWeb: "www.logflorsur.cl", tipoIndustria: "Logística/Distribución", cargoObjetivo: "Gerente de Operaciones, Jefe de Logística" },
  { nombre: "Manufactura La Florida Industrial", region: "Metropolitana", comuna: "La Florida", direccion: "Walker Martínez", telefono: "+56224568400", email: "contacto@manflorind.cl", sitioWeb: "www.manflorind.cl", tipoIndustria: "Manufactura/Industrial", cargoObjetivo: "Jefe de Producción, Gerente de Operaciones" },
  { nombre: "Productos La Florida Express", region: "Metropolitana", comuna: "La Florida", direccion: "Av. La Florida", telefono: "+56225679500", email: "contacto@prodflorex.cl", sitioWeb: "www.prodflorex.cl", tipoIndustria: "Distribución/Industrial", cargoObjetivo: "Coordinador de Logística, Gerente de Operaciones" },

  // EMPRESAS ADICIONALES MACUL
  { nombre: "Centro Industrial Macul", region: "Metropolitana", comuna: "Macul", direccion: "Quilín", telefono: "+56226789700", email: "contacto@centroindmac.cl", sitioWeb: "www.centroindmac.cl", tipoIndustria: "Manufactura/Industrial", cargoObjetivo: "Gerente de Producción, Jefe de Operaciones" },
  { nombre: "Distribuidora Macul Norte", region: "Metropolitana", comuna: "Macul", direccion: "Av. Grecia", telefono: "+56227890800", email: "contacto@distmacnorte.cl", sitioWeb: "www.distmacnorte.cl", tipoIndustria: "Distribución/Industrial", cargoObjetivo: "Jefe de Logística, Gerente de Operaciones" },
  { nombre: "Logística Macul Express", region: "Metropolitana", comuna: "Macul", direccion: "Departamental", telefono: "+56223457400", email: "contacto@logmacex.cl", sitioWeb: "www.logmacex.cl", tipoIndustria: "Logística/Transporte", cargoObjetivo: "Coordinador de Logística, Gerente de Operaciones" },

  // EMPRESAS ADICIONALES QUINTA NORMAL
  { nombre: "Fábrica Quinta Normal Industrial", region: "Metropolitana", comuna: "Quinta Normal", direccion: "San Pablo", telefono: "+56224568500", email: "contacto@fabqnorind.cl", sitioWeb: "www.fabqnorind.cl", tipoIndustria: "Manufactura/Industrial", cargoObjetivo: "Gerente de Producción, Jefe de Operaciones" },
  { nombre: "Logística Quinta Normal Express", region: "Metropolitana", comuna: "Quinta Normal", direccion: "Carrascal", telefono: "+56225679600", email: "contacto@logqnorex.cl", sitioWeb: "www.logqnorex.cl", tipoIndustria: "Logística/Distribución", cargoObjetivo: "Jefe de Logística, Gerente de Operaciones" },
  { nombre: "Ensamblaje Quinta Normal Tech", region: "Metropolitana", comuna: "Quinta Normal", direccion: "José Joaquín Pérez", telefono: "+56226789800", email: "contacto@ensqnortech.cl", sitioWeb: "www.ensqnortech.cl", tipoIndustria: "Ensamblaje/Industrial", cargoObjetivo: "Coordinador de Producción, Gerente de Operaciones" },

  // EMPRESAS ADICIONALES ESTACIÓN CENTRAL
  { nombre: "Centro Logístico Estación Central", region: "Metropolitana", comuna: "Estación Central", direccion: "Av. Libertador Bernardo O'Higgins", telefono: "+56227890900", email: "contacto@logecent.cl", sitioWeb: "www.logecent.cl", tipoIndustria: "Logística/Distribución", cargoObjetivo: "Gerente de Operaciones, Jefe de Logística" },
  { nombre: "Manufactura Estación Central Industrial", region: "Metropolitana", comuna: "Estación Central", direccion: "Alameda", telefono: "+56223457500", email: "contacto@manecentind.cl", sitioWeb: "www.manecentind.cl", tipoIndustria: "Manufactura/Industrial", cargoObjetivo: "Jefe de Producción, Gerente de Operaciones" },
  { nombre: "Distribuidora Estación Central Express", region: "Metropolitana", comuna: "Estación Central", direccion: "Ecuador", telefono: "+56224568600", email: "contacto@distecentex.cl", sitioWeb: "www.distecentex.cl", tipoIndustria: "Distribución/Industrial", cargoObjetivo: "Coordinador de Logística, Gerente de Operaciones" },

  // EMPRESAS ADICIONALES PROVIDENCIA/LAS CONDES (OFICINAS)
  { nombre: "Corporación Industrial Las Condes", region: "Metropolitana", comuna: "Las Condes", direccion: "Av. Apoquindo", telefono: "+56225680000", email: "contacto@corpindlc.cl", sitioWeb: "www.corpindlc.cl", tipoIndustria: "Manufactura/Industrial", cargoObjetivo: "Gerente General, Director de Operaciones" },
  { nombre: "Grupo Logístico Providencia", region: "Metropolitana", comuna: "Providencia", direccion: "Av. Providencia", telefono: "+56226790000", email: "contacto@gruplogprov.cl", sitioWeb: "www.gruplogprov.cl", tipoIndustria: "Logística/3PL", cargoObjetivo: "Gerente de Operaciones, Director Logístico" },
  { nombre: "Holding Industrial Santiago", region: "Metropolitana", comuna: "Las Condes", direccion: "El Golf", telefono: "+56227891000", email: "contacto@holdindstgo.cl", sitioWeb: "www.holdindstgo.cl", tipoIndustria: "Manufactura/Industrial", cargoObjetivo: "Gerente de Adquisiciones, Director de Operaciones" },

  // EMPRESAS ADICIONALES PARA COMPLETAR 200+
  { nombre: "Centro Industrial Talagante", region: "Metropolitana", comuna: "Talagante", direccion: "Ruta 78", telefono: "+56223457600", email: "contacto@indtalag.cl", sitioWeb: "www.indtalag.cl", tipoIndustria: "Parque Industrial", cargoObjetivo: "Gerente de Operaciones, Coordinador de Desarrollo" },
  { nombre: "Logística Talagante Express", region: "Metropolitana", comuna: "Talagante", direccion: "Camino a Melipilla", telefono: "+56224568700", email: "contacto@logtalex.cl", sitioWeb: "www.logtalex.cl", tipoIndustria: "Logística/Distribución", cargoObjetivo: "Jefe de Logística, Gerente de Operaciones" },
  { nombre: "Industrias Buin", region: "Metropolitana", comuna: "Buin", direccion: "Av. Balmaceda", telefono: "+56225679700", email: "contacto@indbuin.cl", sitioWeb: "www.indbuin.cl", tipoIndustria: "Manufactura/Industrial", cargoObjetivo: "Gerente de Producción, Jefe de Operaciones" },
  { nombre: "Distribuidora Buin Sur", region: "Metropolitana", comuna: "Buin", direccion: "Ruta 5 Sur", telefono: "+56226789900", email: "contacto@distbuinsur.cl", sitioWeb: "www.distbuinsur.cl", tipoIndustria: "Distribución/Industrial", cargoObjetivo: "Jefe de Logística, Gerente de Operaciones" },
  { nombre: "Paine Industrial", region: "Metropolitana", comuna: "Paine", direccion: "Av. Manuel Rodríguez", telefono: "+56227891100", email: "contacto@paineind.cl", sitioWeb: "www.paineind.cl", tipoIndustria: "Manufactura/Industrial", cargoObjetivo: "Coordinador de Producción, Gerente de Operaciones" },
  { nombre: "FedEx Chile", region: "Metropolitana", comuna: "Pudahuel", direccion: "Aeropuerto Internacional", telefono: "+56226001000", email: "contacto@fedex.cl", sitioWeb: "www.fedex.com", tipoIndustria: "Logística/Courier", cargoObjetivo: "Gerente de Operaciones, Jefe de Logística" },
  { nombre: "UPS Chile", region: "Metropolitana", comuna: "Pudahuel", direccion: "Parque Industrial Enea", telefono: "+56226002000", email: "contacto@ups.cl", sitioWeb: "www.ups.com", tipoIndustria: "Logística/Courier", cargoObjetivo: "Jefe de Logística, Gerente de Operaciones" },
  { nombre: "Starken", region: "Metropolitana", comuna: "Pudahuel", direccion: "Av. Pedro Fontova", telefono: "+56226003000", email: "contacto@starken.cl", sitioWeb: "www.starken.cl", tipoIndustria: "Logística/Courier", cargoObjetivo: "Gerente de Operaciones, Coordinador de Logística" },
  { nombre: "Turbus Cargo", region: "Metropolitana", comuna: "Estación Central", direccion: "Terminal Alameda", telefono: "+56226004000", email: "cargo@turbus.cl", sitioWeb: "www.turbus.cl", tipoIndustria: "Logística/Transporte", cargoObjetivo: "Jefe de Logística, Gerente de Operaciones" },
  { nombre: "Pullman Cargo", region: "Metropolitana", comuna: "Santiago", direccion: "Terminal Santiago", telefono: "+56226005000", email: "cargo@pullman.cl", sitioWeb: "www.pullman.cl", tipoIndustria: "Logística/Transporte", cargoObjetivo: "Coordinador de Logística, Gerente de Operaciones" },
  { nombre: "Agunsa Logística", region: "Metropolitana", comuna: "Santiago", direccion: "Av. Andrés Bello", telefono: "+56226006000", email: "contacto@agunsa.cl", sitioWeb: "www.agunsa.com", tipoIndustria: "Logística/3PL", cargoObjetivo: "Gerente de Operaciones, Jefe de Logística" },
  { nombre: "Almacenes Paris - Centro Distribución", region: "Metropolitana", comuna: "Maipú", direccion: "Centro Logístico Maipú", telefono: "+56226007000", email: "contacto@paris.cl", sitioWeb: "www.paris.cl", tipoIndustria: "Distribución/Retail", cargoObjetivo: "Gerente de Operaciones, Jefe de Logística" },
  { nombre: "Ripley - Centro Distribución", region: "Metropolitana", comuna: "Quilicura", direccion: "Centro Logístico Quilicura", telefono: "+56226008000", email: "contacto@ripley.cl", sitioWeb: "www.ripley.cl", tipoIndustria: "Distribución/Retail", cargoObjetivo: "Jefe de Logística, Coordinador de Operaciones" },
  { nombre: "Hites - Centro Distribución", region: "Metropolitana", comuna: "Renca", direccion: "Centro Logístico Renca", telefono: "+56226009000", email: "contacto@hites.com", sitioWeb: "www.hites.com", tipoIndustria: "Distribución/Retail", cargoObjetivo: "Gerente de Operaciones, Jefe de Logística" },
  { nombre: "La Polar - Centro Distribución", region: "Metropolitana", comuna: "San Bernardo", direccion: "Centro Logístico San Bernardo", telefono: "+56226010000", email: "contacto@lapolar.cl", sitioWeb: "www.lapolar.cl", tipoIndustria: "Distribución/Retail", cargoObjetivo: "Coordinador de Logística, Gerente de Operaciones" },
  { nombre: "Easy - Centro Distribución", region: "Metropolitana", comuna: "Pudahuel", direccion: "Centro Logístico Pudahuel", telefono: "+56226011000", email: "contacto@easy.cl", sitioWeb: "www.easy.cl", tipoIndustria: "Distribución/Retail", cargoObjetivo: "Jefe de Logística, Gerente de Operaciones" },
  { nombre: "Construmart - Centro Distribución", region: "Metropolitana", comuna: "Quilicura", direccion: "Av. Los Aromos", telefono: "+56226012000", email: "contacto@construmart.cl", sitioWeb: "www.construmart.cl", tipoIndustria: "Distribución/Construcción", cargoObjetivo: "Gerente de Operaciones, Jefe de Logística" },
  { nombre: "Imperial - Centro Distribución", region: "Metropolitana", comuna: "Quilicura", direccion: "Parque Industrial Quilicura", telefono: "+56226013000", email: "contacto@imperial.cl", sitioWeb: "www.imperial.cl", tipoIndustria: "Distribución/Construcción", cargoObjetivo: "Coordinador de Logística, Gerente de Operaciones" },
  { nombre: "Empresas Lipigas - Centro Distribución", region: "Metropolitana", comuna: "Pudahuel", direccion: "Av. Pedro Fontova", telefono: "+56226014000", email: "contacto@lipigas.cl", sitioWeb: "www.lipigas.cl", tipoIndustria: "Distribución/Combustibles", cargoObjetivo: "Jefe de Logística, Gerente de Operaciones" },
  { nombre: "Gasco - Centro Distribución", region: "Metropolitana", comuna: "Pudahuel", direccion: "Parque Industrial", telefono: "+56226015000", email: "contacto@gasco.cl", sitioWeb: "www.gasco.cl", tipoIndustria: "Distribución/Combustibles", cargoObjetivo: "Gerente de Operaciones, Jefe de Seguridad Industrial" },
  { nombre: "Abastible - Centro Distribución", region: "Metropolitana", comuna: "Quilicura", direccion: "Av. Américo Vespucio", telefono: "+56226016000", email: "contacto@abastible.cl", sitioWeb: "www.abastible.cl", tipoIndustria: "Distribución/Combustibles", cargoObjetivo: "Jefe de Logística, Gerente de Operaciones" },
  { nombre: "Nestlé Chile - Planta Santiago", region: "Metropolitana", comuna: "Maipú", direccion: "Camino Lo Sierra", telefono: "+56226017000", email: "contacto@nestle.cl", sitioWeb: "www.nestle.cl", tipoIndustria: "Manufactura/Alimentos", cargoObjetivo: "Gerente de Producción, Jefe de Operaciones" },
  { nombre: "Carozzi - Planta Santiago", region: "Metropolitana", comuna: "San Bernardo", direccion: "Av. Portales", telefono: "+56226018000", email: "contacto@carozzi.cl", sitioWeb: "www.carozzi.cl", tipoIndustria: "Manufactura/Alimentos", cargoObjetivo: "Coordinador de Producción, Gerente de Operaciones" },
  { nombre: "Soprole - Planta Santiago", region: "Metropolitana", comuna: "Maipú", direccion: "Camino Melipilla", telefono: "+56226019000", email: "contacto@soprole.cl", sitioWeb: "www.soprole.cl", tipoIndustria: "Manufactura/Lácteos", cargoObjetivo: "Jefe de Producción, Gerente de Operaciones" },
  { nombre: "Colun - Centro Distribución Santiago", region: "Metropolitana", comuna: "Quilicura", direccion: "Parque Industrial", telefono: "+56226020000", email: "contacto@colun.cl", sitioWeb: "www.colun.cl", tipoIndustria: "Distribución/Lácteos", cargoObjetivo: "Gerente de Operaciones, Jefe de Logística" },
  { nombre: "Watts - Planta Santiago", region: "Metropolitana", comuna: "San Bernardo", direccion: "Av. Eyzaguirre", telefono: "+56226021000", email: "contacto@watts.cl", sitioWeb: "www.watts.cl", tipoIndustria: "Manufactura/Alimentos", cargoObjetivo: "Coordinador de Producción, Gerente de Operaciones" },
  { nombre: "Ariztía - Planta Santiago", region: "Metropolitana", comuna: "Buin", direccion: "Camino Buin", telefono: "+56226022000", email: "contacto@ariztia.cl", sitioWeb: "www.ariztia.com", tipoIndustria: "Manufactura/Alimentos", cargoObjetivo: "Jefe de Producción, Gerente de Operaciones" },
  { nombre: "AgroSuper - Centro Distribución", region: "Metropolitana", comuna: "San Bernardo", direccion: "Parque Industrial", telefono: "+56226023000", email: "contacto@agrosuper.cl", sitioWeb: "www.agrosuper.com", tipoIndustria: "Distribución/Alimentos", cargoObjetivo: "Gerente de Operaciones, Jefe de Logística" },
  { nombre: "Viña Concha y Toro - Bodega Santiago", region: "Metropolitana", comuna: "Maipú", direccion: "Pirque", telefono: "+56226024000", email: "contacto@conchaytoro.com", sitioWeb: "www.conchaytoro.com", tipoIndustria: "Manufactura/Vinos", cargoObjetivo: "Jefe de Logística, Gerente de Operaciones" },
  { nombre: "Viña Santa Rita - Centro Distribución", region: "Metropolitana", comuna: "Santiago", direccion: "Alto Jahuel", telefono: "+56226025000", email: "contacto@santarita.com", sitioWeb: "www.santarita.com", tipoIndustria: "Distribución/Vinos", cargoObjetivo: "Coordinador de Logística, Gerente de Operaciones" },
  { nombre: "Viña San Pedro - Bodega Santiago", region: "Metropolitana", comuna: "Maipú", direccion: "Molina", telefono: "+56226026000", email: "contacto@sanpedro.cl", sitioWeb: "www.sanpedro.cl", tipoIndustria: "Manufactura/Vinos", cargoObjetivo: "Jefe de Logística, Gerente de Operaciones" },
  { nombre: "Compañía Industrial El Volcán", region: "Metropolitana", comuna: "Santiago", direccion: "Av. Vicuña Mackenna", telefono: "+56226027000", email: "contacto@volcan.cl", sitioWeb: "www.volcan.cl", tipoIndustria: "Manufactura/Cemento", cargoObjetivo: "Gerente de Producción, Jefe de Operaciones" },
  { nombre: "Cemento Melón", region: "Metropolitana", comuna: "Cerrillos", direccion: "Av. Pedro Aguirre Cerda", telefono: "+56226028000", email: "contacto@melon.cl", sitioWeb: "www.melon.cl", tipoIndustria: "Distribución/Construcción", cargoObjetivo: "Jefe de Logística, Gerente de Operaciones" },
];

module.exports = empresasDirectorio;
