name: Enviar docs Boletin Comercial
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 1 *'
jobs:
  send:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm install node-fetch@2
      - name: Checkout papeles
        run: git clone https://${{ secrets.GH_PAT }}@github.com/myp202021/licitacion-santo-tomas.git $HOME/licitacion-santo-tomas
      - name: Enviar email
        env:
          RESEND: ${{ secrets.RESEND }}
          HOME: /home/runner
        run: node scripts/send-boletin-docs.js
